### ISSUE TITLE
the bug "UploadOnSave" still exists

### ISSUE THREAD

**Issue by otterstein** [lukasz-wronski/vscode-ftp-sync#288]
Hi,
Everytime i saved the file, the file uploaded automatically.

this is an annoying bug. Please fix it.

it doesn't work, neither in the normal area nor in the generatedFiles area of the ftp-sync.json file.

Thank you in advance!

**Comment by proweb** [comment]
+1
if i have `"uploadOnSave": false,` it still uploaded automatically

**Comment by franboud** [comment]
Same here.
I revert back to 0.3.8 and the problem is fixed!

**Comment by yashika** [comment]
still upload after set the uploadOnSave item value to false.....ahahahahahah

**Comment by pwbiggs** [comment]
Same here.  "uploadOnSave": false, but I still get uploads automatically.

**Comment by davidfasel** [comment]
Another +1.  Upload on save happens even if "uploadOnSave": false in JSON file.  Tried restarting but still happens.

**Comment by visaviweb** [comment]
+1 
Please, fix it!

**Comment by vyskoczilova** [comment]
+1 have a look on it, please

**Comment by frankverhorst** [comment]
Bug still exist. v0.3.9.
Please fix. Ty.

**Comment by frankverhorst** [comment]
> Same here.
> I revert back to 0.3.8 and the problem is fixed!
Bug still exist. v0.3.9. Please fix. Ty.
@franboud: How did you revert?

**Comment by frankv12** [comment]
> Same here.
> I revert back to 0.3.8 and the problem is fixed!

Bug still exist. v0.3.9. Please fix. Ty.
@franboud: How did you revert?

**Comment by franboud** [comment]
@frankverhorst In VS Code, Extensions panel: there is a gear icon at bottom right of each installed extension. You can click on it and select the option "Install Another Version..." and select 0.3.8.

**Comment by XagguHr** [comment]
solution: https://github.com/lukasz-wronski/vscode-ftp-sync/issues/298#issuecomment-546597127

**Comment by mikhailrepka** [comment]
Issue still here, please fix it
